### ISSUE TITLE
Screenshots in README.md 

### ISSUE THREAD

**Issue by x-a-n-a-x** [jaakaappi/Sophistication#31]
Hello.

I think you should add some screenshots of your project in the README.md file.

Or perhaps on a simple website.. 
Github offers this possibility: https://pages.github.com/

This way, we, players, could check the progress of your project :)

**Comment by jaakaappi** [comment]
Hi,

Actually, there are several screenshots for each big update on my web page (http://jaakaappi.pieso.me/sophistication.html) that I for some reason have not linked to the readme. I'll add a link to the page. Out of curiosity, how did you find my project?

**Comment by x-a-n-a-x** [comment]
I am a fan and contributer of OpenRA (https://github.com/OpenRA/OpenRA) and another player that I know, likes Civilization V. I just searched for Civilization V alternatives and I found your project :)
